alkemyTech/OT287-client

package-lock.json, package.json, public/index.html, src/App.js, src/components/Header/BrandLogo.js, src/components/Header/Header.js, src/components/Header/HeaderContainer.js, src/components/Header/Navbar/BurgerMenu.js, src/components/Header/Navbar/Navbar.js, src/index.js, src/styles/theme.js, yarn.lock
- [OT287-22](https://alkemy-labs.atlassian.net/browse/OT287-22)
AS: Usuario
I Want: Visualizar el header de la pagina
To: Acceder a las opciones que tiene
Criterios de aceptación: El componente Header mostrará el logo obtenido del endpoint de datos públicos, y un menú de navegación, ambos elementos de forma dinámica. Para el menú, será un array de ítems de navegación, con un texto y una ruta
=> [Layout] OT287-22: Header 

src/app/pages/dummyHome/home.jsx, src/components/footer/Footer.jsx, src/components/footer/FooterContainer.jsx
- [OT287-](https://alkemy-labs.atlassian.net/browse/OT287-23)
AS: Usuario
I Want: Visualizar el footer de la pagina
To: Tener informacion extra sobre la misma
Criterios de aceptación: Deberá mostrar nombre, logo y link a redes sociales de la Organización. Estos datos serán obtenidos del endpoint de datos públicos.
3 columnas
Logo de la ONG Con nombre
Links de la web
Links de redes sociales
Figma example:
=> [Layout] Ot287 23-Footer 

package-lock.json, package.json, src/components/Alert/Alert.jsx, yarn.lock
- [OT287-](https://alkemy-labs.atlassian.net/browse/OT287-21?atlOrigin=eyJpIjoiZGQzYTFjYjI4YTg4NDAxNDk4NGE5OTI0MTk3NTIzNzAiLCJwIjoiaiJ9)
AS: Usuario
I Want:  Visualizar alertas de una forma estandarizada
To: Confirmar la realización de una acción y obtener un feedback positivo o negativo al realizarla
=> [OT287-21] Setup Alertas

.env.example, src/app/routes/index.jsx, src/components/RegisterForm/RegisterForm.jsx
Re-added the files:
- .env.example
- src\components\RegisterForm\RegisterForm.jsx
Edited routes and re-added:
<Route path="/register" element={<RegisterFormContainer />} />
=> [OT287-24] FIX: Restoring 'Register Form' deleted files

src/components/LoginForm/LoginForm.jsx, src/components/LoginForm/LoginFormContainer.jsx, src/components/LoginForm/loginForm.css
Fixed CSS rules, which was affecting other components imgs.
Added path using .env for login form instead of hardcoding it.
=> [OT287-25] FIX: Login Form > CSS file and absolute path

src/components/Header/Header.jsx
=> [Fix] Header: z-index and position

src/components/LoginForm/LoginFormContainer.jsx, src/components/RegisterForm/RegisterFormContainer.jsx
- [OT287-35](https://alkemy-labs.atlassian.net/browse/OT287-35?atlOrigin=eyJpIjoiNTI2ZTMyMjFjMzU5NGRkZDk0NzJkYTYwNWNjZjhlNjgiLCJwIjoiaiJ9)
AS: Usuario
I Want: Poder autenticarme de forma correcta
To: Poder usar la pagina
Criterios de aceptación: Actualmente, disponemos de los endpoints para registro y login en el servidor, y los formularios del Frontend.
En base al servicio creado para manejar peticiones HTTP, se deberán conectar los formularios para que realicen las peticiones al servidor, mostrando un mensaje de error en el caso de que la petición falle, y redirigiendo al usuario a la ruta base / en el caso de que la autenticación sea exitosa.
Redirige al usuario a la ruta base / en el caso de que la autenticación sea exitosa.
Mensaje de error en el caso de que la petición falle
=> [OT287-35] Connect httpService to login and register forms

src/components/News/MediaCard.jsx, src/pages/MainLayout/index.jsx, src/routes/index.jsx
…d outlet components, Fix MediaCard route from news to novedades
-Fix Routes in Router of Client
-Add MainLayout taht contains Header, Footer and Outlet (React Router Dom) components
-Fix MediaCard route navigate, change from 'news' to 'novedades',
=> Fix routes in Router of Client

src/components/BackOffice/Activities/Activities.jsx, src/components/BackOffice/Activities/ActivitiesContainer.jsx, src/components/BackOffice/BackOfficeContainer.jsx, src/routes/index.jsx
- [OT287-61](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT287/boards/381?modal=detail&selectedIssue=OT287-61)
I Want: Listar todas las Actividades existentes
To: Gestionar el contenido de forma dinámica
Criterios de aceptación: Al ingresar a la ruta /backoffice/activities, mostrará el listado de Actividades para el usuario administrador en una tabla. Obtendrá los datos del endpoint de listado de Actividades, en el caso de que aún no esté listo, los obtendrá desde un array que representarán los datos. Esta listado se mostrará como una tabla que contendrá el nombre de la actividad y las acciones para editarla o eliminarla.
=> [OT287-61]  /backoffice/activities dataTable

src/components/Home/HomeContainer.jsx
- Se eliminó el header del componente Home
=> [FIX] delete header from home component

src/components/BackOffice/BackOfficeContainer.jsx, src/components/BackOffice/users/Users.jsx, src/routes/index.jsx
=> [FIX] fix back-office/users route and style to match header 

src/components/Home/Home.jsx, src/components/Home/HomeContainer.jsx, src/components/footer/Footer.jsx
- [OT287-59](https://alkemy-labs.atlassian.net/browse/OT287-59)
AS: Desarrollador
I Want: Vincular el listado de Novedades con API
To: Mostrar el contenido dinámicamente
Criterios de aceptación: Vincular pantallas de listado y detalle con backend
https://user-images.githubusercontent.com/70545509/193111119-ae65b98f-cee9-420e-9ebd-4cc9d1787f79.mp4
=> [OT287-59] Connect news backend/front

src/components/Forms/LoginForm/LoginFormContainer.jsx, src/components/Forms/RegisterForm/RegisterFormContainer.jsx
- [OT287-66](https://alkemy-labs.atlassian.net/browse/OT287-66)
AS: Usuario
I Want: ingresar al sitio ya logueado, de forma automática
To: navegar el sitio rápidamente
Criterios de aceptación: Cuando el usuario se registre en el sitio, deberá loguearse automáticamente y redirigirse a la ruta base. Para ello, es necesario modificar el servidor para que devuelva el token una vez creado el usuario, y almacenar el mismo en el lado del cliente
=>  [OT287-66] Logic to login user after registration, save user data, and redirect

src/components/Forms/LoginForm/LoginFormContainer.jsx, src/components/Forms/RegisterForm/RegisterFormContainer.jsx, src/components/Header/Header.jsx, src/components/Header/HeaderContainer.jsx, src/components/Logout/Logout.jsx, src/routes/index.jsx
- [OT287-71](https://alkemy-labs.atlassian.net/browse/OT287-71)
AS: Usuario
I Want: Cerrar mi sesión
To: Desloguearme de la pagina
Criterios de aceptación: El cierre de sesión se realizará desde el cliente, eliminando todos los datos del usuario desde localStorage, y desde el store de Redux
=> [OT287-71] logout (erase user data) functionality, Dynamic header buttons

src/components/BackOffice/news/DeleteModal.jsx, src/components/BackOffice/news/News.jsx, src/components/BackOffice/news/NewsContainer.jsx, src/routes/index.jsx, src/services/httpService.js
- [OT287- 65](https://alkemy-labs.atlassian.net/browse/OT287-65)
I Want: Eliminar una Novedad existente
To: Moderar el contenido no deseado
Criterios de aceptación: Al hacer click en el botón eliminar, mostrar una alerta de confirmación. En el caso de confirmar realizar la petición DELETE al endpoint para eliminar el elemento, y quitarlo de la vista
=> [BackOffice] - Add Delete funtionality in backoffice News

src/components/BackOffice/users/Users.jsx, src/components/BackOffice/users/UsersContainer.jsx
- [OT287-58]()
I Want: Actualizar un usuario
To: Mantener los datos de Usuarios del proyecto actualizados
***como se necesita obtener los id`s de los usuarios para hacer la actualización(put) de los mismos, se procedió a hacer la conexión con el servidor, anteriormente los datos estaban hardcodeados.**
=> [OT287-58]  Connect users backend/front

src/components/BackOffice/BackOfficeContainer.jsx, src/components/Forms/OrganizationForm/EditOrganizationContainer.jsx, src/components/Forms/OrganizationForm/EditOrganizationForm.jsx, src/components/Home/Home.jsx, src/components/Home/HomeContainer.jsx, src/components/News/NewsCards.jsx, src/routes/index.jsx, src/services/httpService.js
add fields to organization form, pre-fill them with org info, update endpoint, fix for httpservice
- [OT287-79](https://alkemy-labs.atlassian.net/browse/OT287-79)
AS: usuario administrador
I Want: editar los campos de contacto a la Organización
To: mostrar la información de la mejor manera posible. 
Criterios de aceptación:
Crear una migración para agregar las urls de redes sociales a una Organización. Se deberán agregar url de Facebook, Linkedin e Instagram
=> [OT287-79] Front: Agregar campos de contacto a organizations

package-lock.json, src/components/BackOffice/BackOfficeContainer.jsx, src/components/BackOffice/Testimonials/Testimonials.jsx, src/components/BackOffice/Testimonials/TestimonialsContainer.jsx, src/routes/index.jsx
- [OT287-83](https://alkemy-labs.atlassian.net/browse/OT287-83)
WANT: Listar todos los Testimonios existentes
TO: Gestionar el contenido de forma dinámica
Criterios de aceptación: Al ingresar a la ruta /backoffice/testimonials, mostrará el listado de Testimonios. Obtendrá los datos del endpoint de listado, en el caso de que aún no esté listo, los obtendrá desde un array que representarán los datos. Este listado contendrá el nombre de la persona y las acciones de edición y eliminación.
Mobile view
Desktop
=> [OT287-83] Client: Screen Listado de Testimonios (backoffice)

src/components/Forms/RegisterForm/RegisterForm.jsx
- Changed button height to match Login
- Added Typography to send user to login screen
- Added height so footer wouldn't be over the screen end
=> Fixes on Login Screen Layout and functionality

src/components/BackOffice/Testimonials/TestimonialDeleteModal.jsx, src/components/BackOffice/Testimonials/Testimonials.jsx, src/components/BackOffice/Testimonials/TestimonialsContainer.jsx
- [OT287-88](https://alkemy-labs.atlassian.net/browse/OT287-88)
I Want: Eliminar un testimonio existente
To: Moderar el contenido no deseado
Criterios de aceptación: Al hacer click en el botón eliminar, mostrar una alerta de confirmación. En el caso de confirmar realizar la petición DELETE al endpoint para eliminar el elemento, y quitarlo de la vista
=>  [OT287-88] Delete a testimonial from BackOffice

src/components/BackOffice/news/News.jsx
- [OT287-65]
Repetitive code is removed  without affecting functionality
=> [FIX- OT287-65 ] Fix Icon delete button

src/components/BackOffice/Testimonials/Testimonials.jsx, src/components/Forms/TestimonialsForm/TestimonialForm.jsx, src/components/Forms/TestimonialsForm/TestimonialFormContainer.jsx, src/components/Forms/TestimonialsForm/ckEditor.css, src/routes/index.jsx, src/schemas/testimonials.js
- [OT287-84](https://alkemy-labs.atlassian.net/browse/OT287-84?atlOrigin=eyJpIjoiMzdhNmMyODZhY2FlNGM4NmE2NzRjN2RlMWYwOWFkNDAiLCJwIjoiaiJ9)
AS:Usuario administrador
I Want:Crear o editar un testimonio existente
To:Mantener el contenido actualizado
Criterios de aceptación: El mismo contendrá los campos Nombre (en el modelo activities es name), Imagen y Contenido.
Para el contenido, utilizar la librería CKEditor. El objetivo es crear un formulario reutilizable para las acciones de edición como de creación. Para esto, deberá poder comportarse de forma diferente según recibe un objeto o no.
**BD**
**BD**
=> [BackOffice] OT287-84: Create and edit testimonial

src/components/BackOffice/Activities/Activities.jsx, src/components/BackOffice/users/Users.jsx, src/components/Contact/ContactScreen.jsx, src/components/Forms/LoginForm/LoginForm.jsx, src/components/Header/Header.jsx, src/components/Home/Home.jsx, src/components/Home/HomeContainer.jsx, src/components/Members/MediaCard.jsx, src/components/Members/MembersCards.jsx, src/components/Members/MembersContainer.jsx, src/components/News/MediaCard.jsx, src/components/News/NewById.jsx, src/components/News/NewByIdContainer.jsx, src/components/News/NewsCards.jsx, src/components/News/NewsContainer.jsx, src/routes/index.jsx
- [OT287-103](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT287/boards/381?modal=detail&selectedIssue=OT287-103)
COMO: Desarrollador
QUIERO: Unificar los estilos
PARA: Mejorar la calidad del código
Criterios de aceptación: Realizar modificaciones en la plantilla existente según la imagen de la ONG: Modificar los colores principales y secundarios, buscar una tipografía similar a la del logo y editar elementos principales para adaptarlo a la misma
[screen-capture (1).webm](https://user-images.githubusercontent.com/96206226/193963494-625d948a-079e-4ae7-adc1-e392ad4af011.webm)
[screen-capture.webm](https://user-images.githubusercontent.com/96206226/193963511-f8e20ea1-f694-4e45-8a0b-f4b381980ac6.webm)
[screen-capture (2).webm](https://user-images.githubusercontent.com/96206226/19 …
=> [OT287-103] unifying styles & principals elements according to figma 

src/components/BackOffice/AddButton.jsx, src/components/BackOffice/Categories/Categories.jsx, src/components/BackOffice/Categories/CategoriesContainer.jsx, src/components/BackOffice/ItemCard.jsx, src/components/BackOffice/Items.jsx, src/components/Header/Header.jsx
- [OT287-112](https://alkemy-labs.atlassian.net/browse/OT287-112)
AS: administrador
Want: Revisar el diseño de Categorias
To: Verificar la adaptabilidad de la vista
Criterios de aceptación: Verificar la adaptabilidad a dispositivos móviles de los diferentes elementos y aplicar las correcciones necesarias para que pueda visualizarse correctamente. Aprovechar para terminar de refinar los elementos que se crean pertinentes
- Edited buttons to better follow the design of the rest of the page.
- Fixed spacing and layout for mobile view
- Added sticky position to (+) button which was otherwise scrolling with the list.
mobile view
https://user-images.githubusercontent.com/547180/194139629-c5d1cc17-0522-4e0d-8620-b6e41dd72020.mp4
desktop view
highlight
=> [OT287-112] ABM BackOffice  Categories - Design Revision

src/components/News/MediaCard.jsx, src/components/News/NewById.jsx, src/components/News/NewByIdContainer.jsx, src/components/News/NewsCards.jsx, src/components/News/NewsContainer.jsx, src/components/News/newById.css
- [OT287-109](https://alkemy-labs.atlassian.net/browse/OT287-109)
AS: Usuario
I Want: Revisar el diseño de Novedad
To: Verificar la adaptabilidad de la vista
Criterios de aceptación: Verificar la adaptabilidad a dispositivos móviles de los diferentes elementos y aplicar las correcciones necesarias para que pueda visualizarse correctamente. Aprovechar para terminar de refinar los elementos que se crean pertinentes
=> [OT 287-109] News Screen and News Details review design

src/components/Header/Header.jsx, src/components/Header/HeaderContainer.jsx
- [OT287- fix-header ]()
fix-header 
[screen-capture (3).webm](https://user-images.githubusercontent.com/96206226/194441391-41b887dd-7f68-463e-b0b8-2bbf14edd48e.webm)
[screen-capture (2).webm](https://user-images.githubusercontent.com/96206226/194441406-c2c8f2e2-66b3-4d4d-bb7e-cf1488baef87.webm)
=> OT287-fix-header only

src/components/BackOffice/BackOffice.jsx, src/components/BackOffice/Testimonials/TestimonialDeleteModal.jsx, src/components/BackOffice/Testimonials/Testimonials.jsx, src/components/BackOffice/Testimonials/TestimonialsContainer.jsx, src/components/Forms/TestimonialsForm/TestimonialForm.jsx, src/styles/theme.js
- [OT287-113]()
AS: Usuario
I Want: Revisar el diseño de Testimonios
To: Verificar la adaptabilidad de la vista
Criterios de aceptación: Verificar la adaptabilidad a dispositivos móviles de los diferentes elementos y aplicar las correcciones necesarias para que pueda visualizarse correctamente. Aprovechar para terminar de refinar los elementos que se crean pertinentes
Changes:
1. Changed from px to rem units
2. Improved table height, width and position
3. Improved table header style
4. Fixed typos
5. Fixed z-Index conflict between delete modal and header
6. Improved responsiveness
7. Improved form width and margins
https://user-images.githubusercontent.com/74195715/194415803-d0c3f785-e8e5-4366-8479-803362a142ea.mp4
=> [OT287-113] ABM testimonials - design revision

src/components/MyProfile/MyProfileContainer.jsx
Se conectó el servicio de httpService al componente MyProfileContainer para poder ver los datos desplegados en pantalla. Anteriormente había que harcodear el token en el header de axios para poder tener acceso a ellos.
=> [FIX] connect httpService to get my profile data

src/components/Forms/LoginForm/LoginFormContainer.jsx, src/components/Header/HeaderContainer.jsx
Adding functionality to profile/backoffice button depending on role
User > My profile
Admin > Back office
=> [OT287-Fix-#003] Adding functionality to profile/backoffice button depending on role

src/components/BackOffice/Activities/Activities.jsx
- [OT287-]()
- aling center buttons Activities table back office
BEFORE:
AFTER:
=> OT287-fix-alingButtons

src/components/Home/Home.jsx, src/components/Home/HomeContainer.jsx, src/components/Slider/Slider.jsx
1- Se corrigieron errores de eslint y de propTypes
2- Se corrigen alineaciones de componentes y cambio de estilo botones 'Ver Todos'
3-Se agrega texto e imágenes al Slider 
https://user-images.githubusercontent.com/85040647/195429660-6e69f04f-a361-4ef8-b3b2-0101fea848ad.mp4
=> [OT287 - Fix - #023 ] -Fix Slider in Home, fix eslint and PropTypes errors

src/components/Forms/EditUserProfile/EditUserProfile.jsx, src/components/Forms/EditUserProfile/EditUserProfileContainer.jsx, src/components/MyProfile/MyProfile.jsx
- [OT287-130](https://alkemy-labs.atlassian.net/browse/OT287-130)
Most of the functionality was handled by Eber due to an issue with card instructions for an Org card.  Thanks @ebereber :)
I simply improved some layout options and set buttons as per design, and changed error handling. Fixed some eslint issues too.
AS:
I Want:
To:
AS: usuario
I Want: actualizar los usuarios
To: mantener la información actualizada.
Criterios de aceptación:
PUT /users/:id - Deberá validar que el miembro existe y actualizarla, caso contrario devolver un error. También se deberá re-setear el token JWT en caso de que un usuario (administrador o no) actualizé su propio perfil.
=> [OT287-130] Endpoint Actualización usuarios

src/components/Contact/ContactScreen.jsx, src/components/Forms/ContactForm/ContactForm.jsx
Fixear el layuout de contacto para botones y espaciado de secciones, sacar autofocus, y que los botones usen el theme principal para q pegue con el resto de secciones
=> [OT287-Fix-#030] Contact us: Layout and buttons changes in contact section

src/components/BackOffice/Activities/ActivitiesContainer.jsx, src/components/BackOffice/Categories/CategoriesContainer.jsx, src/components/BackOffice/Contacts/ContactsContainer.jsx, src/components/BackOffice/Testimonials/TestimonialsContainer.jsx, src/components/BackOffice/news/NewsContainer.jsx, src/components/BackOffice/users/UsersContainer.jsx, src/components/Loader/Loader.jsx
- [OT287-126](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT287/boards/381?modal=detail&selectedIssue=OT287-126)
COMO: Usuario Administrador
QUIERO: Visualizar un loader
PARA: Tener un feedback al cargar un recurso
Criterios de aceptación: Crear un loader componente loader reutilizable, utilizando la librería [npm: react-loader-spinner](https://www.npmjs.com/package/react-loader-spinner)  (en el caso de tener otra librería de preferencia, es posible implementarla).
[screen-capture (8).webm](https://user-images.githubusercontent.com/96206226/195465361-33fe02f4-43ca-40f5-80bc-9b3c60476a34.webm)
[screen-capture (10).webm](https://user-images.githubusercontent.com/96206226/195465215-0c79e00b-13f9-4170-9590-2c3a77f0516d.webm)
=> [OT287-126]  setUp Loader at backOffice

src/components/BackOffice/Testimonials/Testimonials.jsx, src/components/BackOffice/Testimonials/TestimonialsContainer.jsx
Testimonial deleteModal wasn't working.
Before:
After:
=> [FIX] OT287-F34: Fix on testimonials deleteModal

src/components/BackOffice/Categories/Categories.jsx, src/components/BackOffice/Categories/CategoriesContainer.jsx
=> [FIX] OT287-F19: Modify Categories look to table style

src/components/BackOffice/Activities/Activities.jsx, src/components/BackOffice/BackOfficeContainer.jsx, src/components/BackOffice/users/Users.jsx, src/routes/index.jsx
- [OT287-Fix-#006]()
backOffice routes changed to english language
[screen-capture (13).webm](https://user-images.githubusercontent.com/96206226/195617490-408e2c62-a0bf-4d04-8ceb-b99a17c618bd.webm)
=> [OT287-Fix-#006] backOffice routes english language

src/components/Home/Home.jsx, src/components/Home/HomeContainer.jsx, src/components/Members/MediaCard.jsx, src/components/Members/MemberBanner.jsx, src/components/Members/MembersCards.jsx, src/components/Members/MembersContainer.jsx
Se corrigió el estilo en la pantalla 'Sobre Nosotros' , se agregó banner para mostrar detalles de cada miembro.
https://user-images.githubusercontent.com/85040647/195665385-78eaf3a3-026c-41b0-9f45-1e1392cbb838.mp4
=> [OT287- Fix - #040] -Style changes in SobreNosotros Screen

src/components/Forms/TestimonialsForm/TestimonialForm.jsx, src/components/Forms/TestimonialsForm/TestimonialFormContainer.jsx, src/components/Testimonials/TestimonialCard.jsx, src/components/Testimonials/Testimonials.jsx, src/components/Testimonials/TestimonialsContainer.jsx, src/routes/index.jsx
- [OT287-Testimonials]
- Se creó la página de testimonios.
- Se realizó el enrutado con el formulario para crear nuevos testimonios. 
- En cuanto a las cards que envuelven a los testimonios se les dio medidas fijas para que su tamaño no dependa de el contenido y queden todas iguales. También se limitó el numero de caracteres dentro de las cards para que no se desborde el texto. Si se supera cierta cantidad aparecerá un botón '...ver más'  que desplegará lo que resta del contenido.
- No logré hacer funcionar CKEditor con material ui. Los testimonios se renderizan con los tags <p <strong, etc.... 
En la [documentación ](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/css.html)de CKEditor dice _**'...is compatible with most of the popular CSS frameworks'**_ …
=> [OT287-TESTIMONIALS] add testimonials page

src/components/PrivateRoute/PrivateRoute.jsx
- [OT287-131](https://alkemy-labs.atlassian.net/browse/OT287-131?atlOrigin=eyJpIjoiY2YyYTUxZmNiMWE4NDBlNDgxZGM2YmZhY2FiODM5MDIiLCJwIjoiaiJ9)
COMO: Usuario
QUIERO: Ser redirigdo a home cuando intento acceder a las rutas protegidas
PARA: Saber a que rutas tengo acceso y cuales no
Criterios de aceptación: Agregar lógica para tener seguridad en las rutas del frontend: Para ingresar a las secciones de gestión del backoffice, el usuario debe tener un rol de administrador. Para la ruta de edición de perfil, debe estar logueado. Si intenta ingresar a una ruta a la que no tiene permiso, debe ser redirigido al home.
=> [OT287-131 ]Protect Routes

src/components/Header/Header.jsx, src/components/Header/HeaderContainer.jsx, src/components/Header/Navbar/BurgerMenu.jsx
Improved mobile navigation menu design
Before:
After:
https://user-images.githubusercontent.com/74195715/195714597-b6caf951-7bef-4e6f-b7df-75a58859cd27.mp4
=> [Layout] OT287: mobile menu design

src/components/MyProfile/MyProfileContainer.jsx
-Redirects user to logout upon deleting it.
- Deletes user data (from logout page).
=> [OT287-Fix-#041] Profile > Delete : Logout deleted user

src/components/BackOffice/DrawerMenu.jsx
- Se dejó fijo el Drawer Menu
Antes
Ahora
=> [FIX] Drawer Menu fixed

package.json, src/components/Forms/NewsForm/NewsFormContainer.jsx, src/components/Layout/AWSFileDelete.js
Create AWSDeleteFile and use it in NewsForm to delete old image when it's changed.
**New library implemented...the old one it's bugged in the delete option.**
=> OT287-F49: AWS delete file function

src/components/BackOffice/BackOfficeContainer.jsx, src/components/BackOffice/DrawerOptions.jsx, src/components/Header/Header.jsx
1- Se dio clase active a botones en drawer del back-office
https://user-images.githubusercontent.com/85040647/195867363-4a4fedd2-be06-4b82-9324-94aeeb80bc5c.mp4
=> [OT287 - Fix - #004] - Add active class to buttons in drawer backoffice

src/components/BackOffice/BackOfficeContainer.jsx, src/components/BackOffice/Organizations/OrganizationsContainer.jsx, src/components/BackOffice/Organizations/Organizatios.jsx, src/components/BackOffice/Slides/Slides.jsx, src/components/BackOffice/Slides/SlidesContainer.jsx, src/components/Forms/OrganizationForm/EditOrganizationContainer.jsx, src/components/Forms/SlidesForm/SlidesForm.jsx, src/components/Forms/SlidesForm/SlidesFormContainer.jsx, src/routes/index.jsx, src/schemas/slides.js
- [OT287-035]()
- backoffice Organizations table (read/delete)
- backoffice Slides tables (read/delete)
- backoffice Slides forms(create/update)
[screen-capture (16).webm](https://user-images.githubusercontent.com/96206226/195964997-762fc746-91c2-4c99-a9a3-7d5e951a21ed.webm)
=> [OT287 - Fix - #035] - backoffice Organizations and Slides tables(read/delete)-forms(create/update)

src/components/Testimonials/TestimonialCard.jsx
=> - [OT287-Fix-#065] Add image to avatar tag in testimonials

src/components/Forms/NewsForm/NewsForm.jsx, src/components/Forms/NewsForm/NewsFormContainer.jsx, src/components/Layout/AWSFileDelete.js, src/components/Layout/AWSFileUpload.js
=> OT287-F48: Implemented timestamp in file name and folder system

src/components/BackOffice/news/NewsContainer.jsx, src/components/Forms/NewsForm/NewsForm.jsx, src/components/Forms/NewsForm/NewsFormContainer.jsx, src/components/Layout/AWSFileDelete.js, src/components/Layout/AWSFileUpload.js, src/components/Layout/DeleteModal.jsx
=> OT287-F53: Delete image from AWS bucket when delete news

src/components/BackOffice/news/NewsContainer.jsx, src/components/Forms/NewsForm/NewsForm.jsx, src/components/Forms/NewsForm/NewsFormContainer.jsx, src/components/Layout/AWSFileDelete.js, src/components/Layout/AWSFileUpload.js, src/components/Layout/DeleteModal.jsx
Pasaba que de la forma anterior a veces no se renombraba por completo el archivo (faltaban los segundos), trayendo problemas...lo cambié a función con async/await para intentar evitar que esto suceda.
=> [FIX] Change renaming method to ensure full file rename

src/components/footer/Footer.jsx
Fix logo, HR, fix spacing and add transition to footer links
=> [OT287-Fix-#067] Footer: Fix logo, HR, fix spacing and add transition to footer links

src/components/Home/Home.jsx, src/components/Home/HomeContainer.jsx, src/components/Slider/Slider.jsx
Se agregó petición a ruta Slides para renderizar en componente 'Home' y se elimina código sobrante.
https://user-images.githubusercontent.com/85040647/196309572-071f86d2-907f-4a71-9055-f1838ca6b87c.mp4
=> [OT287 - Fix - #063] - Add slides petition and delete leftover code

src/components/BackOffice/BackOfficeContainer.jsx, src/components/BackOffice/DrawerOptions.jsx
- [OT287-069]()
- When you clic as Admin at "Edit Profile" button, should navigate to my profile data and with posibility to edit it.
[screen-capture (17).webm](https://user-images.githubusercontent.com/96206226/196516095-9e79e3e6-cc57-4065-90ee-d90e2e8804eb.webm)
=> [OT287 - Fix - #069] isAdmin-profile

src/components/Header/HeaderContainer.jsx, src/components/footer/FooterContainer.jsx
- Removed "contribuye" option from header and footer
=> [OT287-FIX-#012]: Removed "contribuye" option from header and footer

src/routes/index.jsx
- Logged out or normal user : redirects to home.
- Admin: redirects to backoffice.
=> [OT287-Fix-#073] Add redirection for invalid routes

src/components/Forms/UserEditFormBackOffice/EditUserContainer.jsx, src/components/Forms/UserEditFormBackOffice/EditUserForm.jsx, src/routes/index.jsx
- [OT287-054]()
As and Admin user you can create a new "standar" user and then edit it, even the role attribute.
=> [OT287-Fix-#054] BackOffice: User create & edit form

src/components/Forms/ActivitiesForm/ActivitiesForm.jsx, src/components/Forms/ActivitiesForm/ActivitiesFormContainer.jsx, src/components/Forms/CategoriesForm/CategoriesForm.jsx, src/components/Forms/CategoriesForm/CategoriesFormContainer.jsx, src/components/Forms/MembersForm/MembersForm.jsx, src/components/Forms/NewsForm/NewsForm.jsx, src/components/Forms/OrganizationForm/EditOrganizationForm.jsx, src/components/Forms/SlidesForm/SlidesForm.jsx, src/components/Forms/SlidesForm/SlidesFormContainer.jsx, src/components/Forms/TestimonialsForm/TestimonialForm.jsx
- Added save and cancel button on all create forms
- Normalized design.
- Gave correct redirection for cancel and for post-save.
News
Activities
Categories
Testimonials
Organizations
Slides
Members
=> [OT287-Fix-#038] BackOffice: Normalizing save and cancel buttons on create forms in backoffice

src/components/BackOffice/BackOffice.jsx, src/components/BackOffice/BackOfficeContainer.jsx
=> [OT287-Fix-#072] Deleting Add button from edit, create and specific backoffice menus

src/components/Activity/Activity.jsx, src/components/BackOffice/Activities/Activities.jsx, src/components/BackOffice/Testimonials/Testimonials.jsx, src/components/BackOffice/news/News.jsx, src/components/News/MediaCard.jsx, src/components/News/NewById.jsx, src/components/Testimonials/TestimonialCard.jsx
Muestro evidencia solo del circuito news, pero lo implementé en activities y en testimonials también
=> [FIX] OT287-F46: rich text visualization

src/components/Activity/Activities.jsx, src/components/Activity/ActivitiesCard.jsx, src/components/Activity/ActivitiesContainer.jsx, src/components/Header/HeaderContainer.jsx, src/components/footer/FooterContainer.jsx, src/routes/index.jsx
added /activities page and added activities route to header and footer
=> added /activities component and route 

src/components/BackOffice/Activities/Activities.jsx
=> [OT287-Fix-#075] Activities BO: Layout normalization for news table in backoffice

src/components/Forms/LoginForm/LoginForm.jsx
=> [OT287-Fix-#076] Login: Fixing login image positioning

src/components/Header/HeaderContainer.jsx, src/components/footer/FooterContainer.jsx
updated header and footer elements positioning
=> updated header and footer

src/components/Activity/ActivitiesCard.jsx
=> [FIX] Fix for long text in activities cards

src/components/Header/BrandLogo.jsx, src/components/Header/Header.jsx, src/components/Header/HeaderContainer.jsx
=> [OT287-Fix-#070] Fixing heading pending issues for login and register buttons

src/components/BackOffice/Slides/Organization.jsx, src/components/BackOffice/Slides/SlidesContainer.jsx, src/components/Forms/SlidesForm/SlidesForm.jsx, src/components/Forms/SlidesForm/SlidesFormContainer.jsx
…dit form
BEFORE
Table
Form
AFTER
Table 
Form
=> [OT287-Fix-#081] Fix and normalize Slide table, hide unnecessary fields in table and form

src/components/BackOffice/users/Users.jsx, src/components/BackOffice/users/UsersContainer.jsx, src/components/Forms/NewsForm/NewsForm.jsx, src/components/Forms/UserEditFormBackOffice/EditUserContainer.jsx, src/components/Forms/UserEditFormBackOffice/EditUserForm.jsx, src/components/Layout/FormInputImage.jsx
=> [OT287-Fix-#082] Fix and normalize user table

src/components/PrivateRoute/PrivateRoute.jsx, src/routes/index.jsx
https://user-images.githubusercontent.com/75214315/196832863-9c3ec226-8717-49fa-8b48-06b106b1d35e.mp4
=> [OT287 - FIX - #56] - Protegiendo ruta de edicion de perfil de el usuario

src/components/BackOffice/Members/Members.jsx, src/components/BackOffice/Members/MembersContainer.jsx, src/components/Members/MediaCard.jsx
=> [OT287-Fix-#083] Fix and normalize Members table 

src/components/BackOffice/BackOffice.jsx, src/components/BackOffice/BackOfficeContainer.jsx, src/components/BackOffice/DrawerOptions.jsx
link redirects to profile, not profile edit. Fixed some eslint issues as well.
=> [OT287-Fix-#084] Backoffice: Fix eslint issues and make button read 'Profile' 

src/components/BackOffice/BackOffice.jsx, src/components/BackOffice/BackOfficeContainer.jsx, src/components/BackOffice/DrawerOptions.jsx, src/index.css
=> Fix Login Screen - Horizontal scrollbar

src/components/Testimonials/TestimonialCard.jsx
=> [Testimonial Ver mas] spacing Fix

src/components/BackOffice/BackOffice.jsx, src/components/BackOffice/BackOfficeLanding.jsx
=> Landing back office

public/index.html, src/components/Contact/ContactScreen.jsx, src/components/Header/Header.jsx, src/components/Home/Home.jsx, src/components/Members/MemberBanner.jsx, src/components/Slider/Slider.jsx, src/routes/index.jsx
Fixed various things shown in console.
=> [FIX] Frontend Console Fixes

src/components/BackOffice/Activities/Activities.jsx, src/components/BackOffice/BackOffice.jsx, src/components/BackOffice/Categories/Categories.jsx, src/components/BackOffice/Contacts/Contacts.jsx, src/components/BackOffice/Contacts/ContactsContainer.jsx, src/components/BackOffice/DrawerMenu.jsx, src/components/BackOffice/DrawerOptions.jsx, src/components/BackOffice/Members/Members.jsx, src/components/BackOffice/Slides/Slides.jsx, src/components/BackOffice/Testimonials/Testimonials.jsx, src/components/BackOffice/news/News.jsx, src/components/BackOffice/users/Users.jsx, src/components/Forms/CategoriesForm/CategoriesFormContainer.jsx, src/components/Forms/NewsForm/NewsForm.jsx, src/components/Forms/NewsForm/NewsFormContainer.jsx, src/components/Forms/OrganizationForm/EditOrganizationContainer.jsx, src/components/Forms/SlidesForm/SlidesForm.jsx, src/components/Forms/SlidesForm/SlidesFormContainer.jsx, src/components/Forms/UserEditFormBackOffice/EditUserContainer.jsx, src/components/Forms/UserEditFormBackOffice/EditUserForm.jsx, src/components/Header/Header.jsx, src/components/Header/HeaderContainer.jsx, src/components/Header/Navbar/BurgerMenu.jsx, src/components/Layout/DeleteModal.jsx, src/components/MyProfile/MyProfile.jsx, src/schemas/users.js
Yeah, they are a lot of files, but mostly are changes in proptypes or things like that.
=> [FIX] Console fixes in backoffice
